# Generated by Django 5.2.7 on 2025-10-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_train_name_alter_station_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination', 'distance')},
        ),
    ]
