# Generated by Django 5.2.7 on 2025-11-04 17:49

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0006_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=station.models.create_custom_path
            ),
        ),
    ]
